# FROM: https://github.com/LISAChallengeOfficial/sample-model-templates/blob/main/python/Dockerfile

# Define the base of your image.
# Specifying `--platform=linux/amd64` ensures compatibility when building on Apple Silicon (M1/M2).
# Always pin the version (e.g., python:3.10-slim) to ensure reproducibility.
FROM python:3.10-slim

# Set the working directory for the COPY, RUN, and ENTRYPOINT commands.
WORKDIR /vcasellesb-LISA

COPY SynthSR SynthSR
COPY HD-BET HD-BET
COPY trained_models trained_models

# Install essential build tools such as gcc/g++ that may be needed to compile certain Python packages.
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    gcc \
    g++ && \
    pip install --upgrade pip && \
    pip install --no-cache-dir tensorflow-cpu && \
    pip install --no-cache-dir torch && \
    pip install --no-cache-dir PyWavelets && \
    pip install --no-cache-dir -e ./SynthSR && \
    pip install --no-cache-dir -e ./HD-BET && \
    rm -rf /var/lib/apt/lists/*

COPY src src

# Set the main command to run your model script when the container starts.
ENTRYPOINT ["python", "-m", "src.run_dockerized", "-npp_hdbet", "6", "-npe_hdbet", "6", "--nthreads_synthsr", "4"]